Repository IanButcher/BitQualy--LAFALDA, pull requests merged in 2024-10, with the labels that each got.

#24 New Features from formularios and evaluaciones
  Schemas/evaluacionSchema.js
  erroresGPT.txt
  public/formularios.css
  routes/evaluacionRoutes.js
  views/evals/awnser.ejs
  views/evals/evaluacion.ejs
  views/evals/evaluaciones.ejs
  views/evals/new.ejs
  views/forms/formularios.ejs
  views/forms/new.ejs
Labels: bug, enhancement

#27 Git config and workflow
  .github/workflows/protect-schemas.yml
  index.js
Labels: git fixes

#30 Git config and workflow
  .github/workflows/prevent-main-errors.yml
  .github/workflows/protect-schemas.yml
  index.js
Labels: bug fixes, duplicate, git fixes

#33 Frontend awnser css
  public/awnser.css
  views/evals/awnser.ejs
Labels: bug fixes, duplicate, frontend enhancement

#36 Lovefool
  public/evaluacion.css
  views/evals/evaluacion.ejs
Labels: frontend enhancement

#39 Evaluaciones frontend
  public/evaluacion.css
  public/formularios.css
  views/evals/evaluacion.ejs
  views/forms/new.ejs
  views/home/homeAdmin.ejs
Labels: bug fixes, duplicate, help wanted, small aditions, frontend enhancement

#41 Backend login y auth (in process)
  Schemas/baseUserSchema.js
  index.js
  middleware/passportConfig.js
  routes/login.js
  views/index.ejs
Labels: enhancement

#43 Arreglos css
  public/evaluacion.css
  public/navbar.css
  public/newUser.css
  public/update.css
  routes/login.js
  views/empls/empleados.ejs
  views/evals/evaluacion.ejs
  views/evals/evaluaciones.ejs
  views/forms/new.ejs
  views/forms/update.ejs
  views/home/homeAdmin.ejs
  views/newUsers.ejs
Labels: bug fixes, help wanted, small aditions, frontend enhancement

#47 Backend login y auth
  Schemas/adminSchema.js
  index.js
  middleware/passportConfig.js
  routes/empleadoRoutes.js
  routes/evaluacionRoutes.js
  routes/evaluadorRoutes.js
  routes/formularioRoutes.js
  routes/intermediarioRoutes.js
  routes/login.js
  seedEmpleados.js
  seedEvaluadores.js
  seedReguladores.js
  views/empls/empleado.ejs
  views/empls/empleados.ejs
  views/evalrs/evaluador.ejs
  views/evalrs/evaluadores.ejs
  views/evals/awnser.ejs
  views/evals/evaluacion.ejs
  views/evals/evaluaciones.ejs
  views/evals/new.ejs
  views/newUsers.ejs
  views/partials/navbarInter.ejs
  views/regs/regulador.ejs
  views/regs/reguladores.ejs
Labels: bug fixes, duplicate, enhancement, small aditions

#49 Arreglos 15 10
  public/formularios.css
  views/empls/empleado.ejs
  views/empls/empleados.ejs
  views/evalrs/evaluador.ejs
  views/forms/formularios.ejs
  views/regs/regulador.ejs
Labels: bug fixes, small aditions

#52 nose m rindo profe :shipit:
  public/img/user.png
  views/empls/empleado.ejs
  views/evals/evaluaciones.ejs
  views/regs/regulador.ejs
Labels: bug fixes, small aditions

#69 log out function
  routes/login.js
Labels: enhancement, small aditions

#75 My account user
  Schemas/baseUserSchema.js
  Schemas/evaluacionSchema.js
  Schemas/formularioSchema.js
  adminUser.js
  public/uploads/images/1729703632081.jpg
  public/uploads/images/1729861109372.png
  public/uploads/images/1729863402687.jpg
  public/uploads/images/1729863607879.png
  public/uploads/images/1729863767922.png
  public/uploads/images/1729866708762.jpg
  public/uploads/images/1729867881549.png
  public/uploads/images/1729869429031.PNG
  public/uploads/images/1729871359384.png
  public/uploads/images/1729871370411.png
  public/uploads/images/1729872130240.jpg
  public/uploads/images/1729874397641.png
  public/uploads/images/1729874519261.png
  public/uploads/images/1729874767708.png
  routes/empleadoRoutes.js
  routes/evaluacionRoutes.js
  routes/formularioRoutes.js
  routes/login.js
  views/myAccount.ejs
  views/newUsers.ejs
  views/partials/header.ejs
  views/partials/headerU.ejs
  views/userprofile/userprofile.ejs
Labels: bug fixes, enhancement, small aditions, git fixes

#79 Panel derecho para que sea mas cool :+1: :ambulance: :cat2:
  public/newForm.css
  views/forms/new.ejs
Labels: bug fixes, small aditions

#81 Arreglitos frontend cele
  public/update.css
  views/empls/empleado.ejs
  views/forms/new.ejs
  views/forms/update.ejs
Labels: small aditions, frontend enhancement

#84 detalles
  public/newForm.css
  views/forms/formularios.ejs
  views/forms/new.ejs
  views/forms/update.ejs
Labels: bug fixes, small aditions
